development:
  adapter: mysql2
  database: hello_world_dev
  reconnect: false
  encoding: utf8
  collation: utf8_general_ci
  host: localhost
  pool: 5
  username: dev
  password: '321321'
test:
  adapter: mysql2
  database: hello_world_test
  reconnect: false
  encoding: utf8
  collation: utf8_general_ci
  host: localhost
  pool: 1
  username: dev
  password: '321321'
production:
  adapter: mysql2
  database: hello
  reconnect: false
  encoding: utf8
  collation: utf8_general_ci
  host: localhost
  pool: 5
  username: <%= ENV['RAILS_APP_DATABASE_USER'] %>
  password: <%= ENV['RAILS_APP_DATABASE_PASSWORD'] %>